defmodule MaxElixirPokeApi do
  alias MaxElixirPokeApi.Helper

  def resource(:berry), do: Helper.do_request("berry")
  def resource(:berry_firmness), do: Helper.do_request("berry-firmness")
  def resource(:berry_flavor), do: Helper.do_request("berry-flavor")
  def resource(:contest_type), do: Helper.do_request("contest-type")
  def resource(:contest_effect), do: Helper.do_request("contest-effect")
  def resource(:super_contest_effect), do: Helper.do_request("super-contest-effect")
  def resource(:encounter_method), do: Helper.do_request("encounter-method")
  def resource(:encounter_condition), do: Helper.do_request("encounter-condition")
  def resource(:encounter_condition_value), do: Helper.do_request("encounter-condition-value")
  def resource(:evolution_chain), do: Helper.do_request("evolution-chain")
  def resource(:evolution_trigger), do: Helper.do_request("evolution-trigger")
  def resource(:generation), do: Helper.do_request("generation")
  def resource(:pokedex), do: Helper.do_request("pokedex")
  def resource(:version), do: Helper.do_request("version")
  def resource(:version_group), do: Helper.do_request("version-group")
  def resource(:item), do: Helper.do_request("item")
  def resource(:item_attribute), do: Helper.do_request("item-attribute")
  def resource(:item_category), do: Helper.do_request("item-category")
  def resource(:item_fling_effect), do: Helper.do_request("item-fling-effect")
  def resource(:item_pocket), do: Helper.do_request("item-pocket")
  def resource(:location), do: Helper.do_request("location")
  def resource(:location_area), do: Helper.do_request("location-area")
  def resource(:pal_park_area), do: Helper.do_request("pal-park-area")
  def resource(:region), do: Helper.do_request("region")
  def resource(:machine), do: Helper.do_request("machine")
  def resource(:move), do: Helper.do_request("move")
  def resource(:move_ailment), do: Helper.do_request("move-ailment")
  def resource(:move_battle_style), do: Helper.do_request("move-battle-style")
  def resource(:move_category), do: Helper.do_request("move-category")
  def resource(:move_damage_class), do: Helper.do_request("move-damage-class")
  def resource(:move_learn_method), do: Helper.do_request("move-learn-method")
  def resource(:move_target), do: Helper.do_request("move-target")
  def resource(:ability), do: Helper.do_request("ability")
  def resource(:characteristic), do: Helper.do_request("characteristic")
  def resource(:egg_group), do: Helper.do_request("egg-group")
  def resource(:gender), do: Helper.do_request("gender")
  def resource(:growth_rate), do: Helper.do_request("growth-rate")
  def resource(:nature), do: Helper.do_request("nature")
  def resource(:pokeathlon_stat), do: Helper.do_request("pokeathlon-stat")
  def resource(:pokemon), do: Helper.do_request("pokemon")
  def resource(:pokemon_color), do: Helper.do_request("pokemon-color")
  def resource(:pokemon_form), do: Helper.do_request("pokemon-form")
  def resource(:pokemon_habitat), do: Helper.do_request("pokemon-habitat")
  def resource(:pokemon_shape), do: Helper.do_request("pokemon-shape")
  def resource(:pokemon_species), do: Helper.do_request("pokemon-species")
  def resource(:stat), do: Helper.do_request("stat")
  def resource(:type), do: Helper.do_request("type")
  def resource(:language), do: Helper.do_request("language")
  
  def resource(_), do: {:error, %{reason: "resource invalid."}}
end
